### ISSUE TITLE
🐞 Cannot connect to self-hosted instance on iOS

### ISSUE THREAD

**Issue by lllama** [aimok04/kitshn#228]
### What happened?

I can't connect to a self-hosted instance, either by hostname or IP address. Kitshn connects with the "log in with web browser" button but then doesn't let me do anything else to complete the authentication.

I've also tried tapping the bug report button but that does nothing either.

Sorry I can't give any more details but I seem to be stuck at the first hurdle.

### App Version

Unknown - latest from App Store

### Server Version

v1.5.35 (via proxmox helper scripts)

### Platform(s)

iOS

**Comment by rhyst** [comment]
I think I am also experiencing this on Android. Perhaps related to Tandoor v2? Untare stopped working so I switched to kitshn but I can't sign in with password, API token, or web browser.

**Comment by lllama** [comment]
I thought it might be something like that but I'm pretty sure I'm on v1. This is the error I'm getting:

![image](https://github.com/user-attachments/assets/8dec7ec0-5439-4ce7-be6e-2a2ddc57016f)

**Comment by rhyst** [comment]
Ignore my comment, I was literally signing in with the wrong password 😆

**Comment by arnaudandre22** [comment]
Hello,  

I have the exact same issue but my tandoor server is "brand new" (version 2.0.1).  Latest ios app.

Btw, I directly use an IP adress so it's not a DNS issue (to be exact, mine is : http://192.168.2.100:8568).
The server is reachable with the exact same adress in the web browser.

Edit : I tested with an android app and it's working fine....except I realised that my 2.X version wasn't supported without the beta.  Just to be sure, I installed the besta ios version and it's the same problem.

Best regards

**Comment by aimok04** [comment]
Hi @lllama @arnaudandre22 

Maybe this is happening because you use the http protocol, but I thought I fixed this on iOS with 994aaaeb23efb6f42447c31da5a9f1227b0a6524.

I'll check if I can reproduce this!

**Comment by aimok04** [comment]
@rhyst 

I should add a *show password* button 😆

**Comment by lllama** [comment]
Thanks @aimok04. I _think_ you're right. I installed Mealie alongside Tandoor and its iOS client had a similar issue but its error message specifically called out the lack of TLS. So I'm setting up nginx proxy manager - I'll report back on whether that makes a difference.

**Comment by lllama** [comment]
So I'm still having the issue when using an HTTPS connection. The funny thing is that I have managed to connect once before but that involved using Tailscale to access the network and then logging in via IP address. It worked for a bit but then lost access to the recipes (I could still access some of the functionality). I shall investigate further.

**Comment by nsutcliffe** [comment]
I'm having the same issue as @lllama ; I'm hosting behind Nginx and am using https (although I've self signed the certificate, it makes me wonder if that has anything to do with it?). I'm happy to share the link to my repository privately or gather any information you'd like @aimok04 :)

**Comment by nsutcliffe** [comment]
@aimok04 I've curled <myinstance>/api/ as this seems to be how you check the instance, and it'll be failing for me because this is what is received:

`curl: (35) schannel: next InitializeSecurityContext failed: SEC_E_CERT_EXPIRED (0x80090328) - The received certificate has expired.`

It's a bit late here but tomorrow I'll renew my certificate and see if it resolves the issue and will confirm back

**Comment by lllama** [comment]
A further bit of info: if I `tail` the access logs on the tandoor container, then I don't see any requests come in when I enter the url. If I click "log in with the browser" then a bunch of requests come through. So something seems to be failing to trigger the requests which is then reported as not being able to connect.

**Comment by NextBlaubeere** [comment]
i am also stuck with http for now, unfortunatelly. 

i get the same error message as in the picture. kitshn seems to do not allow self signed certificates.

**Comment by lllama** [comment]
Someone on Discord suggested checking the Local Network permissions for the app and it turns out they were disabled. Flipping the toggle to allow access seems to have solved it.

**Comment by lllama** [comment]
@NextBlaubeere I don't know what your setup is but I was able to do what is described in this video: https://youtu.be/qlcVx-k-02E and get nginx proxy manager running with LetsEncrypt certificates. (Will depend on you having a domain and a DNS server)

**Comment by aimok04** [comment]
Hey @lllama 

Thanks for figuring that out! :)
I didn't even know that such a toggle exited.

I'll try to add an error message when trying to connect to a local server with the setting turned off!

**Comment by lllama** [comment]
Awesome. You should be able to check and prompt the user for permissions. No idea how to do it though but I know other apps ask for permission. 😅

**Comment by NextBlaubeere** [comment]
> Someone on Discord suggested checking the Local Network permissions for the app and it turns out they were disabled. Flipping the toggle to allow access seems to have solved it.

That is on iOS, right? No such permission exists on Android unfortunatelly. At least I did not find it. :-(


> [@NextBlaubeere](https://github.com/NextBlaubeere) I don't know what your setup is but I was able to do what is described in this video: https://youtu.be/qlcVx-k-02E and get nginx proxy manager running with LetsEncrypt certificates. (Will depend on you having a domain and a DNS server)

No thank you. I want to keep it local only with a *.lan domain. That wouldn't work with a certificate that is not self signed.

**Comment by arnaudandre22** [comment]
> Someone on Discord suggested checking the Local Network permissions for the app and it turns out they were disabled. Flipping the toggle to allow access seems to have solved it.

Thanks !  Works like a charm after toggling it on :)

**Comment by nsutcliffe** [comment]
@lllama Sorry for the delay in getting back to you, had some issues with automatically refreshing my certificate and wanted to fix it properly. I've updated that now and that resolved the connection issue I reported above (so the issue was an expired certificate was being rejected by the app).

Edit: @aimok04 sorry getting confused with who I'm tagging! Loving your app

**Comment by lllama** [comment]
@NextBlaubeere I just have my DNS (AWS Route53) return local IP addresses. So technically you'll need external DNS but that's it. None of the hosts are available externally.

**Comment by NextBlaubeere** [comment]
> [@NextBlaubeere](https://github.com/NextBlaubeere) I just have my DNS (AWS Route53) return local IP addresses. So technically you'll need external DNS but that's it. None of the hosts are available externally.

I know about dns-01 challenge, but that is not how i want to run this service. Thank you for mentioning it though.

seems like http only for me at the moment. :-P

**Comment by lllama** [comment]
Last option would be to use https://mkcert.dev/ or similar to create your own CA and then install the CA cert on your phone. Don't know how to do that on Android though.

**Comment by aimok04** [comment]
Hi @NextBlaubeere 

I never actually tested kitshn with a self-signed certificate.
I'll check if I can solve this! :)

**Comment by aimok04** [comment]
I closed this issue in favour of #240 and #241.

**Comment by NextBlaubeere** [comment]
> > [@NextBlaubeere](https://github.com/NextBlaubeere) I just have my DNS (AWS Route53) return local IP addresses. So technically you'll need external DNS but that's it. None of the hosts are available externally.
> 
> I know about dns-01 challenge, but that is not how i want to run this service. Thank you for mentioning it though.
> 
> seems like http only for me at the moment. :-P

I just found out you can install a certificate system wide on android. It does not work with my internal lan-only domain and https. :-)
